### ISSUE TITLE
デザインの検討

### ISSUE THREAD

**Issue by sksat** [core-rocket/website#8]
多分このままhugo使うと思うので良さげなテーマを[公式のまとめ](https://themes.gohugo.io)から選定する．もしくは自分たちでフルスクラッチしてもヨシ！

**Comment by ztacti** [comment]
描きたい気持ちあるけど中途半端な感じになりそうだから、とりあえずhugoから選んで後から拡張していけばいいかと思います。

**Comment by sksat** [comment]
まあ後からやり直すことも全然できるのでとりあえず良さげなの選んで弄っていきましょう．
良さげなテーマあったら各位このIssueに書いていってください．

**Comment by Yukuro** [comment]
(事後かもしれませんが)良さそうなの2点
- [Universal](https://themes.gohugo.io/hugo-universal-theme/)
- [Creative](https://themes.gohugo.io/creative/)

**Comment by sksat** [comment]
Universal良さそうですねえ．ライセンスもMITだし．

Creativeはシンプルなポートフォリオ用ってかんじですね．これはこれで良いけど今のサイトの移行，ということを考えると向かないかもしれない．

**Comment by sksat** [comment]
とりあえず#12 でUniversal使ってやってみてます

**Comment by sksat** [comment]
所々微妙ですが[こんなかんじ](https://deploy-preview-12--core-rocket.netlify.com)でどうですかね

**Comment by sksat** [comment]
諸々追加してとりあえず見られるようにはなりました．後で直すのはいくらでもできるのでとりあえず #12 をマージしようと思います．
